using System.Runtime.CompilerServices;

namespace Duzenleme.Localization;

// Birden çok alanda geçen metinler: bir kez ve tutarlı çevrilsin. Alanın kendi dosyasına aynı çeviriyle tekrar yazmak
// serbesttir, farklı çeviri test hatasıdır. İngilizce: cümle düzeninde büyük harf, samimi "you" (Türkçedeki "sen"),
// Microsoft terimleri ("notification area", "Settings > Apps > Startup").
internal static partial class En
{
    [ModuleInitializer]
    internal static void AddCommon() => Add(
    [
        new("Ana sayfa", "Home"),
        new("Araçlar", "Tools"),
        new("Arşivler", "Archives"),
        new("Ayarlar", "Settings"),
        new("Aç", "Open"),
        new("Açık", "Light"),
        new("Başlangıç ayarlarını aç", "Open Startup settings"),
        new("Belgeler", "Documents"),
        new("Bölmeler", "Panels"),
        new("Dosyalar", "Files"),
        new("Gelişmiş", "Advanced"),
        new("Geri al", "Undo"),
        new("Geri alındı", "Undone"),
        new("Gizle", "Hide"),
        new("Gizli", "Hidden"),
        new("Göster", "Show"),
        new("Klasör adı", "Folder name"),
        new("Klasörler", "Folders"),
        new("Klasörü oluştur", "Create folder"),
        new("Koyu", "Dark"),
        new("Kısayol kutusu", "Shortcut box"),
        new("Kısayollar", "Shortcuts"),
        new("Masaüstü", "Desktop"),
        new("Masaüstü simgelerini yalnızca bölmelerde göster", "Show desktop icons only in panels"),
        new("Masaüstünde klasör yok.", "There are no folders on the desktop."),
        new("Masaüstünde var", "On the desktop"),
        new("Masaüstündeki klasörler", "Folders on the desktop"),
        new("Masaüstünü göster", "Show desktop"),
        new("Masaüstünü şimdi düzenle", "Tidy up the desktop now"),
        new("Mavi", "Blue"),
        new("Mor", "Purple"),
        new("Müzik", "Music"),
        new("Not", "Note"),
        new("Otomatik taşıma", "Auto-move"),
        new("Pembe", "Pink"),
        new("Renk", "Color"),
        new("Resimler", "Pictures"),
        new("Saat", "Clock"),
        new("Son taşımayı geri al", "Undo last move"),
        new("Tarih", "Date"),
        new("Test örneğinde değiştirilmez.", "Not changed in the test instance."),
        new("Turuncu", "Orange"),
        new("Uygulamalar", "Apps"),
        new("Vazgeç", "Cancel"),
        new("Videolar", "Videos"),
        new("Widget ekle", "Add widget"),
        new("Widget'lar", "Widgets"),
        new("Widget'ları öne getir (5 sn)", "Bring widgets to front (5 s)"),
        new("Yapılacaklar", "To-do"),
        new("Yeni klasör", "New folder"),
        new("Yeşil", "Green"),
        new("Yok", "None"),
        new("{0}'i aç", "Open {0}"),
        new("Kaldır", "Remove"),
        new("Sil", "Delete"),
        new("Kaydet", "Save"),
        new("Uygula", "Apply"),
        new("Kapat", "Close"),
        new("Yeniden adlandır…", "Rename…"),
        new("Başlığı değiştir…", "Change title…"),
        new("Başlık", "Title"),
        new("Şimdi düzenle", "Tidy up now"),
        new("Varsayılana döndür", "Restore defaults"),
        new("Arka plan", "Background"),
        new("Vurgu rengi", "Accent color"),
        new("Cam", "Glass"),
    ]);
}
