using System.Runtime.CompilerServices;

namespace Duzenleme.Localization;

// 2.1 P6 "Yeni widget'lar": takvim, geri sayım, zamanlayıcı/Pomodoro/kronometre, dünya saati, sistem durumu, Geri Dönüşüm
// Kutusu, klasör portalları, ekleme kataloğu, saat/tarih/not/bölme eklemeleri. Terim: "bölme" = "panel".
internal static partial class En
{
    [ModuleInitializer]
    internal static void AddP6() => Add(
    [
        // Ekleme kataloğu ("Widget ekle", Widget'lar sayfası)
        new("Saat ve bilgi", "Clocks and info"),
        new("Büyük dijital saat", "Large digital clock"),
        new("Gün, ay ve haftalık şerit", "Day, month and a weekly strip"),
        new("Yapışkan not; yazdıkça kaydedilir", "Sticky note; saved as you type"),
        new("Onay kutulu liste; işaretledikçe kaydedilir", "Checklist; saved as you check items off"),
        new("Sekmeli uygulama rafı; tek tıkla açar", "Tabbed app shelf; opens things with one click"),
        new("Takvim", "Calendar"),
        new("Aylık takvim; ay ay gezinilir", "Monthly calendar; browse month by month"),
        new("Geri sayım", "Countdown"),
        new("Geri sayım · {0}", "Countdown · {0}"),
        new("Bir güne kaç gün kaldı (tatil, doğum günü…)", "Days left until a date (vacation, birthday…)"),
        new("Zamanlayıcı", "Timer"),
        new("Geri sayan zamanlayıcı; süre dolunca haber verir. Kronometre de olur.",
            "A timer that tells you when time is up. It can also be a stopwatch."),
        new("Pomodoro", "Pomodoro"),
        new("25 dakika odak, 5 dakika mola; dört turda bir uzun mola", "25 minutes of focus, 5-minute breaks; a long break every four rounds"),
        new("Dünya saati", "World clock"),
        new("Dünya saati · {0}", "World clock · {0}"),
        new("Başka şehirlerde saat kaç, kaç saat fark var", "The time in other cities and how far ahead or behind they are"),
        new("Sistem durumu", "System status"),
        new("İşlemci, bellek, disk ve pil", "Processor, memory, disk and battery"),
        new("Geri Dönüşüm Kutusu", "Recycle Bin"),
        new("Kaç öğe var, ne kadar yer tutuyor; boşaltmadan önce sorar", "How many items and how much space; asks before emptying"),
        new("Başka klasör…", "Other folder…"),
        new("Bilgisayardaki herhangi bir klasörü bölmede göster (masaüstünde olması gerekmez)",
            "Show any folder on this PC in a panel (it doesn't have to be on the desktop)"),
        new("{0} klasörünün içi, en yeni üstte", "Contents of {0}, newest first"),
        new("Windows klasörü", "Windows folder"),
        new("Bölmede gösterilecek klasörü seç", "Choose the folder to show in the panel"),
        new("{0} masaüstüne eklendi.", "{0} was added to the desktop."),
        new("İndirilenler", "Downloads"),
        new("Ekran görüntüleri", "Screenshots"),

        // Widget adları (Widget'lar listesi, tepsi)
        new("Kısayol kutusu · {0}", "Shortcut box · {0}"),
        new("({0} öğe)", "({0} item)", "({0} items)"),
        new("Bölme · {0}", "Panel · {0}"),
        new("Kronometre", "Stopwatch"),
        new("Zamanlayıcı · {0} dk", "Timer · {0} min"),

        // Yeni widget'ın yeri (tepsi ipucu)
        new("Yapılacaklar listesi", "To-do list"),
        new("Yeni not", "New note"),
        new("Bölme", "Panel"),
        new("ekranın ortasına", "in the center of the screen"),
        new("ekranın sağ üstüne", "at the top right of the screen"),
        new("ekranın sağ altına", "at the bottom right of the screen"),
        new("ekranın üst ortasına", "at the top center of the screen"),
        new("imlecin yanına", "next to the pointer"),
        new("{0} {1} eklendi", "{0} was added {1}"),
        new("Yeni widget'ların yerini Widget'lar sayfasından değiştirebilirsin.", "You can change where new widgets appear on the Widgets page."),
        new(" Widget'ları pencerelerin önüne getirmek için {0}.", " Press {0} to bring widgets in front of windows."),

        // Saat
        new("Günaydın", "Good morning"),
        new("İyi günler", "Good afternoon"),
        new("İyi akşamlar", "Good evening"),
        new("İyi geceler", "Good night"),
        new("Saniyeyi göster", "Show seconds"),
        new("Selam ve gün", "Greeting and day"),
        new("Saat biçimi", "Time format"),
        new("Windows'taki gibi", "Same as Windows"),
        new("24 saat (15:30)", "24-hour (15:30)"),
        new("12 saat (3:30 ÖS)", "12-hour (3:30 PM)"),

        // Tarih
        new("Yıl ve gün adı", "Year and weekday"),
        new("Haftalık şerit", "Weekly strip"),

        // Takvim
        new("Bugün", "Today"),
        new("Hf", "Wk", Context: "hafta"),
        new("Önceki ay", "Previous month"),
        new("Sonraki ay", "Next month"),
        new("Önceki ay (Page Up)", "Previous month (Page Up)"),
        new("Sonraki ay (Page Down)", "Next month (Page Down)"),
        new("Bugüne dön (Home)", "Back to today (Home)"),
        new("Bugüne dön", "Back to today"),
        new("{0}, bugün", "{0}, today"),
        new("Haftanın ilk günü", "First day of the week"),
        new("Dile göre", "Based on language"),
        new("Ay ve düğmeler", "Month and buttons"),
        new("Gün adları", "Day names"),
        new("Hafta numaraları", "Week numbers"),

        // Geri sayım
        new("Bugün!", "Today!"),
        new("gün", "day", "days"),
        new("gün önce", "day ago", "days ago"),
        new("{0}: bugün", "{0}: today"),
        new("{1}: {0} gün kaldı", "{1}: {0} day left", "{1}: {0} days left"),
        new("{1}: {0} gün önceydi", "{1}: {0} day ago", "{1}: {0} days ago"),
        new("Tarihi ve adı değiştir…", "Change date and name…"),
        new("Her yıl yinele", "Repeat every year"),
        new("Etkinliğin adı", "Event name"),
        new("Tarih satırı", "Date line"),
        new("ör. Tatil, Doğum günü", "e.g. Vacation, Birthday"),
        new("Gün", "Date"),
        new("Her yıl yinele (doğum günü, yıl dönümü)", "Repeat every year (birthday, anniversary)"),

        // Zamanlayıcı / Pomodoro / kronometre
        new("+1 dk", "+1 min"),
        new("Sıfırla", "Reset"),
        new("Sıfırla (R)", "Reset (R)"),
        new("Bir dakika ekle", "Add a minute"),
        new("Odak bitti", "Focus session done"),
        new("Uzun mola zamanı.", "Time for a long break."),
        new("Kısa bir mola zamanı.", "Time for a short break."),
        new("Mola bitti", "Break is over"),
        new("Yeniden odaklanma zamanı.", "Time to focus again."),
        new("Süre doldu", "Time's up"),
        new("Süre doldu · {0}", "Time's up · {0}"),
        new("Süre doldu · {0} · Sırada: {1}", "Time's up · {0} · Next: {1}"),
        new("Duraklat", "Pause"),
        new("Başlat", "Start"),
        new("{0} (Boşluk)", "{0} (Space)"),
        new("Boşluk", "Space"),
        new("duraklatıldı", "paused"),
        new("Odak · {0}/{1}", "Focus · {0}/{1}"),
        new("Odak", "Focus"),
        new("Mola", "Break"),
        new("Uzun mola", "Long break"),
        new("Tür", "Mode"),
        new("Süre", "Duration"),
        new("Başka süre…", "Other duration…"),
        new("Odak süresi", "Focus length"),
        new("Sonraki aşama kendiliğinden başlasın", "Start the next phase automatically"),
        new("Süre dolunca bildir", "Notify me when time is up"),
        new("Durum satırı", "Status line"),
        new("İlerleme çubuğu", "Progress bar"),
        new("Düğmeler", "Buttons"),
        new("{0} dk", "{0} min"),
        new("Süre (dakika)", "Duration (minutes)"),

        // Dünya saati
        new("aynı saat", "same time"),
        new("{0} sa", "{0} h"),
        new("{0} sa {1} dk", "{0} h {1} min"),
        new("Yarın", "Tomorrow"),
        new("Dün", "Yesterday"),
        new("Dün / yarın", "Yesterday / tomorrow"),
        new("Saat farkı", "Time difference"),
        new("Saat dilimi bulunamadı", "Time zone not found"),
        new("Yerel saat", "Local time"),
        new("Adını değiştir…", "Rename…"),
        new("Şehrin adı", "City name"),
        new("Ad (boş bırakırsan şehrin kendi adı)", "Name (leave empty to use the city's own name)"),
        new("Yukarı taşı", "Move up"),
        new("Aşağı taşı", "Move down"),
        new("Bu şehri kaldır", "Remove this city"),
        new("Şehir ekle…", "Add city…"),
        new("Şehir ekle", "Add city"),
        new("Satıra sağ tık: adını değiştir, taşı, kaldır", "Right-click a row to rename, move or remove it"),
        new("Henüz şehir yok.", "No cities yet."),
        new("Şehir ya da saat dilimi ara", "Search for a city or time zone"),
        new("Ara", "Search"),
        new("Şehirler", "Cities"),
        new("Ekle", "Add"),
        new("Saat farkı ve yaz saati Windows'un saat dilimlerinden gelir.", "Time differences and daylight saving time come from Windows time zones."),

        // Sistem durumu
        new("İşlemci", "CPU"),
        new("Bellek", "Memory"),
        new("Disk", "Disk"),
        new("Pil", "Battery"),
        new("Açık kalma süresi", "Uptime"),
        new("{0} / {1} · {2}", "{0} / {1} · {2}"),
        new("{0} · şarj oluyor", "{0} · charging"),
        new("{0} · takılı", "{0} · plugged in"),
        new("Disk ({0})", "Disk ({0})"),
        new("{0} boş", "{0} free"),
        new("Görev Yöneticisi'ni aç", "Open Task Manager"),
        new("Güncelleme sıklığı", "Update interval"),
        new("{0} saniyede bir", "Every {0} seconds"),
        new("{0} bayt", "{0} byte", "{0} bytes"),
        new("{0} gün {1} sa", "{0} d {1} h"),

        // Geri Dönüşüm Kutusu
        new("Boşalt…", "Empty…"),
        new("Boşalt", "Empty"),
        new("Boş", "Empty", Context: "kutu"),
        new("{0} öğe", "{0} item", "{0} items"),
        new("{0} · {1}", "{0} · {1}"),
        new("Geri Dönüşüm Kutusu'nu aç", "Open Recycle Bin"),
        new("Geri Dönüşüm Kutusu'nu boşalt", "Empty Recycle Bin"),
        new("Geri Dönüşüm Kutusu'nu boşalt…", "Empty Recycle Bin…"),
        new("Geri Dönüşüm Kutusu'ndaki her şeyi kalıcı olarak siler (önce sorar)", "Permanently deletes everything in the Recycle Bin (asks first)"),
        new("Açmak için çift tıkla", "Double-click to open"),
        new("Öğe sayısı ve boyut", "Item count and size"),
        new("Boşalt düğmesi", "Empty button"),
        new("Yenile", "Refresh"),
        new("Bırakın, Geri Dönüşüm Kutusu'na gitsin", "Drop to move to the Recycle Bin"),
        new("Geri Dönüşüm Kutusu zaten boş", "The Recycle Bin is already empty"),
        new("Silinecek bir şey yok.", "There's nothing to delete."),
        new("Geri Dönüşüm Kutusu boşaltılsın mı?", "Empty the Recycle Bin?"),
        new("{0} ({1}) kalıcı olarak silinecek. Bu geri alınamaz.", "{0} ({1}) will be permanently deleted. This can't be undone."),
        new("Geri Dönüşüm Kutusu'ndaki her şey kalıcı olarak silinecek. Bu geri alınamaz.",
            "Everything in the Recycle Bin will be permanently deleted. This can't be undone."),
        new("Geri Dönüşüm Kutusu boşaltılamadı: {0}", "Couldn't empty the Recycle Bin: {0}"),

        // Bölme: klasör portalı, sıralama
        new("Klasör bulunamadı: {0}", "Folder not found: {0}"),
        new("Başka klasör seç…", "Choose another folder…"),
        new("… ve {0} öğe daha · Klasörde aç", "… and {0} more item · Open folder", "… and {0} more items · Open folder"),
        new("Bilinen klasörler", "Known folders"),
        new("Başka bir klasör…", "Another folder…"),
        new("Sırala", "Sort"),
        new("En yeni üstte", "Newest first"),
        new("En eski üstte", "Oldest first"),
        new("Ada göre", "By name"),
        new("Türe göre", "By type"),
        new("Boyuta göre (büyük üstte)", "By size (largest first)"),
        new("Elle (sürükleyerek)", "Manual (drag to reorder)"),

        // Not
        new("Yazı boyutu: Ctrl + tekerlek", "Text size: Ctrl + wheel"),
        new("Yazı boyutu", "Text size"),
        new("Küçük", "Small"),
        new("Normal", "Normal"),
        new("Büyük", "Large"),
        new("Bitenler alta insin", "Move checked items to the bottom"),

        // Widget menüsü
        new("Boyut: kenarlardan sürükle · {0} · Izgaraya hizala: Shift", "Size: drag the edges · {0} · Snap to grid: Shift"),
    ]);
}
