using System.Runtime.CompilerServices;

namespace Duzenleme.Localization;

// P5 (2.1): ad ve simge, yerinde yeniden adlandırma (F2). Widgets/{TitleEditor, TileRename, ItemRename, IconCatalog, TileItem,
// FenceView, LauncherView, NoteView, WidgetManager, TileStyles.xaml, InputDialog}, Views/{IconPicker, NewFenceDialog,
// WidgetCatalog, WidgetsPage}, Core/FileNames. Terimler: bölme = panel, kısayol kutusu = shortcut box.
internal static partial class En
{
    [ModuleInitializer]
    internal static void AddP5() => Add(
    [
        // Yeniden adlandırma
        new("Yeniden adlandır", "Rename"),
        new("Yeni ad", "New name"),
        new("Bölmeyi yeniden adlandır", "Rename panel"),
        new("Kutuyu yeniden adlandır", "Rename box"),
        new("Listeyi yeniden adlandır", "Rename list"),
        new("Notu yeniden adlandır", "Rename note"),
        new("Sekmeyi yeniden adlandır", "Rename tab"),
        new("Ad (boş bırakırsan varsayılan ad kullanılır)", "Name (leave empty to use the default name)"),
        new("Sekme adı", "Tab name"),
        new("Yeni sekme", "New tab"),
        new("Sekme {0}", "Tab {0}"),
        new("Bir ad yazmalısın.", "Type a name."),
        new("\"{0}\" Windows'a ayrılmış bir ad; başka bir ad seç.", "\"{0}\" is reserved by Windows. Choose another name."),
        new("Ad çok uzun: Windows bu kadar uzun bir yolu açamaz.", "The name is too long: Windows can't open a path this long."),
        new("Ad şu karakterleri içeremez: {0}", "A name can't contain any of these characters: {0}"),
        new("Uzantı değişsin mi?", "Change the file name extension?"),
        new("Dosya adı uzantısını değiştirirsen dosya kullanılamaz hâle gelebilir. Yine de değiştirilsin mi?",
            "If you change a file name extension, the file might become unusable. Change it anyway?"),
        new("Değiştir", "Change"),
        new("Bu adda bir öğe zaten var", "An item with this name already exists"),
        new("Bu klasörde \"{0}\" adında bir öğe var. \"{1}\" olarak adlandırılsın mı?",
            "This folder already has an item named \"{0}\". Name it \"{1}\" instead?"),
        new("Evet", "Yes"),
        new("Hayır", "No"),
        new("\"{0}\" yeniden adlandırılamadı: {1}", "Couldn't rename \"{0}\": {1}"),
        new("\"{0}\" yeniden adlandırılamadı: öğe artık orada değil.", "Couldn't rename \"{0}\": the item is no longer there."),
        new("başka bir programda açık. Kapatıp yeniden dene.", "it's open in another program. Close it and try again."),
        new("Yalnızca kutuda görünen ad değişir; dosyanın adı değişmez.", "Only the name shown in the box changes; the file keeps its name."),
        new("Varsayılan ad ve simge", "Default name and icon"),
        new("Otomatik taşıma kuralları \"{0}\" klasörüne taşıyordu. Kurallar \"{1}\" klasörüne geçsin mi?",
            "Auto-move rules were moving files to the \"{0}\" folder. Switch them to \"{1}\"?"),
        new("Kuralları güncelle", "Update rules"),
        new("Güncellemek için buraya tıkla.", "Click here to update them."),

        // Kutucuklar ve menüler
        new("{0}\n(asıl adı: {1})\n{2}\n(bulunamadı)", "{0}\n(actual name: {1})\n{2}\n(not found)"),
        new("{0}\n(asıl adı: {1})\n{2}", "{0}\n(actual name: {1})\n{2}"),
        new("{0}\n{1}\n(bulunamadı)", "{0}\n{1}\n(not found)"),
        new("Geri Dönüşüm Kutusu'na taşı", "Move to Recycle Bin"),
        new("Widget'tan kaldır", "Remove from widget"),
        new("Bu bölmede ara", "Search this panel"),
        new("Klasör oluşturulamadı: {0}", "Couldn't create the folder: {0}"),
        new("Öğe ekle", "Add item"),
        new("Uygulama ya da dosya…", "App or file…"),
        new("Klasör…", "Folder…"),
        new("Kısayol kutusuna klasör ekle", "Add folders to the shortcut box"),

        // Simge seçici
        new("Simgeyi değiştir", "Change icon"),
        new("Simgeyi değiştir…", "Change icon…"),
        new("Simge seç", "Choose an icon"),
        new("\"{0}\" için simge", "Icon for \"{0}\""),
        new("Simgeler", "Icons"),
        new("Simge", "Icon"),
        new("Varsayılan", "Default"),
        new("Seçilen simge", "Selected icon"),
        new("Windows simgelerinden…", "From Windows icons…"),
        new("Programların ve Windows'un simgelerinden seç (Simge Değiştir penceresi)",
            "Choose from the icons of Windows and your programs (Change Icon window)"),
        new("Resim dosyasından…", "From an image file…"),
        new("PNG, ICO, JPG, BMP ya da GIF; bu bilgisayarda uygulama verisine kopyalanır",
            "PNG, ICO, JPG, BMP or GIF; a copy is kept in the app data on this PC"),
        new("Simge için resim seç", "Choose an image for the icon"),
        new("Bu resim kullanılamadı. En çok 8 MB'lık PNG, ICO, JPG, BMP ya da GIF seç.",
            "This image can't be used. Choose a PNG, ICO, JPG, BMP or GIF file up to 8 MB."),

        // Simge adları (IconCatalog; ekran okuyucu ve ipucu)
        new("Klasör", "Folder"),
        new("Açık klasör", "Open folder"),
        new("Belge", "Document"),
        new("PDF", "PDF"),
        new("Resim", "Picture"),
        new("Video", "Video"),
        new("Arşiv", "Archive"),
        new("Kutu", "Box"),
        new("İndirilenler", "Downloads"),
        new("Bulut", "Cloud"),
        new("Uygulama rafı", "App shelf"),
        new("İş", "Work"),
        new("Kod", "Code"),
        new("Komut satırı", "Command line"),
        new("Veritabanı", "Database"),
        new("Grafik", "Chart"),
        new("Hesap makinesi", "Calculator"),
        new("Posta", "Mail"),
        new("Sohbet", "Chat"),
        new("Takvim", "Calendar"),
        new("Defter", "Notebook"),
        new("Görevler", "Tasks"),
        new("Araç kutusu", "Toolbox"),
        new("Web", "Web"),
        new("Oyunlar", "Games"),
        new("Eklenti", "Add-in"),
        new("Ev", "Home"),
        new("Ofis", "Office"),
        new("Yıldız", "Star"),
        new("Kalp", "Heart"),
        new("Roket", "Rocket"),
        new("Kupa", "Trophy"),
        new("Bayrak", "Flag"),
        new("Raptiye", "Pin"),
        new("Etiket", "Tag"),
        new("Yer işareti", "Bookmark"),
        new("Fikir", "Idea"),
        new("Kitap", "Book"),
        new("Okul", "School"),
        new("Para", "Money"),
        new("Cüzdan", "Wallet"),
        new("Alışveriş", "Shopping"),
        new("Fatura", "Receipt"),
        new("Hediye", "Gift"),
        new("Kamera", "Camera"),
        new("Tasarım", "Design"),
        new("Kulaklık", "Headphones"),
        new("Kişiler", "People"),
        new("Kilit", "Lock"),
        new("Güvenlik", "Security"),
        new("Pırıltı", "Sparkle"),
        new("Doğa", "Nature"),
        new("Evcil hayvan", "Pet"),
        new("Kahve", "Coffee"),
        new("Yemek", "Food"),
        new("Seyahat", "Travel"),
        new("Araba", "Car"),
        new("Spor", "Sports"),

        // Yeni bölme
        new("Yeni bölme", "New panel"),
        new("Yeni bölme…", "New panel…"),
        new("Adını, ne göstereceğini ve simgesini seçerek bölme ekle", "Add a panel and choose its name, what it shows and its icon"),
        new("Ad", "Name"),
        new("ör. Projeler", "e.g. Projects"),
        new("Ne göstersin?", "What should it show?"),
        new("Masaüstünde bu adla yeni klasör", "A new folder on the desktop with this name"),
        new("Var olan bir masaüstü klasörü", "An existing desktop folder"),
        new("Masaüstündeki öğeler", "Items on the desktop"),
        new("Ekle", "Add"),
        new("Yeni klasör için bir ad yaz.", "Type a name for the new folder."),
        new("Masaüstünde bu adda bir klasör var; bölme onu gösterir.",
            "There's already a folder with this name on the desktop; the panel will show it."),
        new("Bir klasör seç.", "Choose a folder."),
        new("\"{0}\" bölmesi masaüstüne eklendi.", "The \"{0}\" panel was added to the desktop."),
    ]);
}
