using System.Runtime.CompilerServices;

namespace Duzenleme.Localization;

// 2.1 tarama: Views/SettingsPage (xaml + kod). Dil satırı En.Settings.cs'te; "Animasyonlar" En.P7.cs'te; ortak metinler
// (Ayarlar, Masaüstü, Gelişmiş, Aç, Kaldır, Sil, Göster/Gizle…) En.Common.cs'te. Terimler: bölme = panel, kutu = box,
// otomatik taşıma = auto-move, tepsi = notification area, Gezgin = File Explorer.
internal static partial class En
{
    [ModuleInitializer]
    internal static void AddSweepSettings() => Add(
    [
        // ---- Genel ----
        new("Genel", "General"),
        new("{0}'in nasıl çalışacağını seç.", "Choose how {0} works."),
        new("Windows ile başlat", "Start with Windows"),
        new("Oturum açınca tepside sessizce başlar; widget'lar ve otomatik taşıma hazır olur.",
            "Starts quietly in the notification area when you sign in, so your widgets and auto-move are ready."),
        new("Taşıma bildirimleri", "Move notifications"),
        new("Bir dosya taşındığında kısa bir bildirim göster.", "Show a short notification when a file is moved."),
        new("Tema", "Theme"),
        new("Bu pencerenin görünümü. Widget'ların görünümü Widget'lar sayfasından ya da widget'a sağ tıklayarak ayarlanır.",
            "How this window looks. To change how widgets look, use the Widgets page or right-click a widget."),
        new("Sistem", "System"),

        // ---- Masaüstü: kutular ----
        new("Hepsini masaüstüne geri koy", "Put all back on the desktop"),
        new("Henüz kutuya taşınan öğe yok. Taşınanlar {0} klasöründe durur.",
            "No items have been moved to boxes yet. Moved items are kept in the {0} folder."),
        new("{0} öğe kutularda; dosyalar {1} klasöründe.",
            "{0} item is in a box; the file is in the {1} folder.",
            "{0} items are in boxes; the files are in the {1} folder."),
        new("{0} öğe masaüstüne döner ve kutularda kalır.",
            "{0} item goes back to the desktop and stays in its box.",
            "{0} items go back to the desktop and stay in their boxes."),
        new("Ortak masaüstündeki öğeler de taşınsın", "Also move items from the Public Desktop"),
        new("Ortak masaüstündeki kısayollar (çoğu uygulamanınki) bu bilgisayardaki tüm hesaplarda görünür. Açarsan kutuya eklediğin böyle bir öğe tüm hesapların masaüstünden kalkar; izin yoksa kutuya yalnızca bağlantı olarak eklenir.",
            "Shortcuts on the Public Desktop (where most apps put theirs) appear for every account on this PC. If you turn this on, an item like that you add to a box leaves every account's desktop; without permission, it's only added to the box as a link."),

        // ---- Masaüstü: göz atma ----
        new("Windows masaüstüne göz atılıyor", "Peeking at the Windows desktop"),
        new("Göz at", "Peek"),
        new("Windows'un masaüstü simgeleri görünür, widget'lar kısa süre çekilir; ekranın üstündeki çubuktan dönülür. Kısayol atanmamış.",
            "Windows desktop icons appear and widgets step aside for a moment; use the bar at the top of the screen to go back. No shortcut assigned."),
        new("Windows'un masaüstü simgeleri görünür, widget'lar kısa süre çekilir; ekranın üstündeki çubuktan dönülür. Kısayol: {0}",
            "Windows desktop icons appear and widgets step aside for a moment; use the bar at the top of the screen to go back. Shortcut: {0}"),
        new("Göz atarken widget'ları gizle", "Hide widgets while peeking"),
        new("Göz atarken açık pencereleri küçült", "Minimize open windows while peeking"),
        new("Win+D gibi; dönünce pencereler geri gelir. Çift tıklayınca masaüstü zaten öndedir.",
            "Like Win+D; your windows come back when you return. When you double-click, the desktop is already in front."),
        new("Kendiliğinden geri dön", "Return automatically"),
        new("1 dakika sonra", "After 1 minute"),
        new("2 dakika sonra", "After 2 minutes"),
        new("5 dakika sonra", "After 5 minutes"),
        new("10 dakika sonra", "After 10 minutes"),
        new("Ben dönene dek", "Never"),

        // ---- Masaüstü: çift tıklama, gizleme, yeni widget'ların yeri ----
        new("Boş masaüstüne çift tıklayınca", "Double-click on the empty desktop"),
        new("Otomatik (önerilen)", "Automatic (recommended)"),
        new("Masaüstünü gizle / göster", "Hide / show desktop"),
        new("Hiçbir şey yapma", "Do nothing"),
        new("Simgeler (ve ayara göre widget'lar) gizlenir; yeniden çift tıklayınca geri gelir.",
            "Icons (and widgets, depending on your settings) are hidden; double-click again to bring them back."),
        new("Windows'un simgeleri görünür, widget'lar kısa süre çekilir; yeniden çift tıklayınca dönülür.",
            "Windows desktop icons appear and widgets step aside for a moment; double-click again to go back."),
        new("Çift tıklama yalnızca Windows'un kendi işini yapar.", "Double-clicking only does what Windows normally does."),
        new("Bölmeler masaüstünü yönetirken Windows masaüstüne göz atar, yoksa masaüstünü gizler/gösterir. Simgeye çift tıklamak yine dosyayı açar.",
            "Peeks at the Windows desktop while panels manage your desktop; otherwise hides or shows the desktop. Double-clicking an icon still opens the file."),
        new("Gizlerken widget'ları da gizle", "Also hide widgets when hiding the desktop"),
        new("Kapalıyken yalnızca masaüstü simgeleri gizlenir; saat, not ve bölmeler kalır.",
            "When off, only desktop icons are hidden; clocks, notes and panels stay."),
        new("Masaüstünü şimdi gizle", "Hide desktop now"),
        new("Kısayol atanmamış", "No shortcut assigned"),
        new("Kısayol: {0}", "Shortcut: {0}"),
        new("Yeni widget'ların yeri", "Where new widgets appear"),
        new("Kısayolla (ör. yeni not) ya da \"Widget ekle\" penceresiyle eklenenler. Yeni widget birkaç saniye vurgulu olarak öne gelir.",
            "For widgets added with a shortcut (like a new note) or from the \"Add widget\" window. A new widget comes to the front, highlighted, for a few seconds."),

        // ---- Masaüstü: sistem simgeleri ----
        new("Sistem simgeleri", "System icons"),
        new("Bu Bilgisayar, Geri Dönüşüm Kutusu, Ağ…", "This PC, Recycle Bin, Network…"),
        new("Gezgin'de aç", "Open in File Explorer"),
        new("Aç: {0}", "Open {0}"),
        new("Görünür", "Visible"),
        new("Bu simgeleri Windows ayarlarından aç/kapat", "Turn these icons on or off in Windows Settings"),
        new("Microsoft Store sürümü bu Windows ayarını kendisi değiştiremez. Açılan Temalar sayfasında \"Masaüstü simgesi ayarları\"na tıkla; buraya dönünce durum yenilenir.",
            "The Microsoft Store version can't change this Windows setting itself. On the Themes page that opens, select \"Desktop icon settings\"; the status here updates when you come back."),
        new("Temalar sayfasını aç", "Open Themes page"),
        new("Masaüstü şu an bölmelerde; açtığın simgeler \"Kısayollar\" bölmesinde görünür.",
            "Your desktop is in panels right now; icons you turn on appear in the \"Shortcuts\" panel."),

        // ---- Klasör simgeleri ----
        new("Klasör simgeleri", "Folder icons"),
        new("Yeni klasöre simge öner", "Suggest icons for new folders"),
        new("Masaüstünde klasör açıp adını verdiğinde bildirim gelir; tıklayınca simge seçici açılır.",
            "When you create and name a folder on the desktop, you get a notification; select it to open the icon picker."),
        new("Tüm klasörlere önerilen simgeyi ver", "Give every folder its suggested icon"),
        new("Özel simgesi olmayan masaüstü klasörlerine adlarına uygun hazır simge verir.",
            "Gives desktop folders that don't have a custom icon a ready-made icon that matches their name."),
        new("Simgeleri ver", "Apply icons"),
        new("{0} klasöre adına uygun simge verildi. Beğenmediğini \"Bir klasörün simgesini değiştir\"den değiştirebilirsin.",
            "{0} folder got an icon that matches its name. If you don't like it, change it under \"Change a folder's icon\".",
            "{0} folders got icons that match their names. If you don't like one, change it under \"Change a folder's icon\"."),
        new("Değişiklik yok: tüm klasörlerin zaten özel simgesi var.", "Nothing changed: every folder already has a custom icon."),
        new("Bir klasörün simgesini değiştir", "Change a folder's icon"),
        new("Masaüstündeki klasörlerden birini seç.", "Choose one of the folders on your desktop."),
        new("özel simge", "custom icon"),
        new("Simge seç: {0}", "Choose an icon for {0}"),

        // ---- Gelişmiş: klavye kısayolları ----
        new("Klavye kısayolları", "Keyboard shortcuts"),
        new("Kutuya tıkla ve yeni tuş birleşimine bas (en az bir Ctrl/Alt/Shift/Win). Silmek için Backspace.",
            "Click a box and press the new key combination (with at least one of Ctrl/Alt/Shift/Win). Press Backspace to clear it."),
        new("Kısayolları varsayılana döndür", "Reset shortcuts to defaults"),
        new("Widget ekle penceresi", "Add widget window"),
        new("Etkin", "Active"),

        // ---- Gelişmiş: yapay zekâ ----
        new("Yapay zekâ ile klasör simgesi (isteğe bağlı)", "AI folder icons (optional)"),
        new("Yapay zekâ ile klasör simgesi", "AI folder icons"),
        new("Kendi Claude API anahtarınla açıklamaya göre simge üret.", "Generate icons from a description with your own Claude API key."),
        new("Claude API anahtarı", "Claude API key"),
        new("Anahtarı girersen klasör simgesi penceresinde yazdığın açıklamaya göre yeni simge üretebilirsin. Anahtar yalnızca bu bilgisayarda, Windows hesabına bağlı şifrelenerek saklanır. Üretim başına küçük bir API ücreti (birkaç sent) Anthropic hesabına yansır. Anahtar zorunlu değil; hazır simgeler anahtarsız çalışır. {0} internete yalnızca anahtarı doğrularken ve sen \"Üret\"e bastığında Anthropic'e bağlanır; simge için yalnızca klasör adı ve yazdığın açıklama gönderilir.",
            "With a key, you can generate new icons in the folder icon window from a description you type. The key is stored only on this PC, encrypted and tied to your Windows account. Each icon costs a small API fee (a few cents), charged to your Anthropic account. A key is optional; the ready-made icons work without one. {0} connects to the internet only to reach Anthropic, when it verifies the key and when you press \"Generate\"; only the folder name and your description are sent."),
        new("Kaydet ve doğrula", "Save and verify"),
        new("Kayıtlı ({0})", "Saved ({0})"),
        new("Eklenmedi", "Not added"),
        new("Anahtar boş", "No key entered"),
        new("Önce anahtarı yapıştır.", "Paste your key first."),
        new("Kaydedilmedi", "Not saved"),
        new("Kaydedildi", "Saved"),
        new("Anahtar doğrulandı. Klasör simgesi penceresinde \"Üret\" artık kullanılabilir.",
            "Key verified. You can now use \"Generate\" in the folder icon window."),
        new("Silindi", "Deleted"),
        new("API anahtarı ayarlardan kaldırıldı. Eski ayar yedeklerinde (yedekler klasörü) şifreli kopyası kalabilir.",
            "The API key was removed from settings. An encrypted copy may remain in older settings backups (the yedekler folder)."),
        new("Anahtarın yoksa: ", "Don't have a key? "),
        new("Neyin gönderildiği: ", "What's sent: "),

        // ---- Gelişmiş: klasör simgelerinin hepsini kaldır ----
        new("Klasör simgelerinin hepsini kaldır", "Remove all folder icons"),
        new("Masaüstündeki klasörlere {0}'in verdiği simgeleri kaldırır. {0}'i kaldırmadan önce kullanabilirsin: simgeler klasörlerin içinde durduğu için kendiliğinden silinmez.",
            "Removes the icons {0} gave to folders on your desktop. Use this before you uninstall {0}: the icons are stored inside the folders, so they aren't deleted automatically."),
        new("Klasör simgelerinin hepsi kaldırılsın mı?", "Remove all folder icons?"),
        new("{0}'in verdiği bütün klasör simgeleri silinir ve klasörler Windows'un varsayılan simgesine döner. Klasörlere ve içlerindeki dosyalara dokunulmaz. Simgeleri yeniden vermek istersen \"Klasör simgeleri\" bölümünü kullan.",
            "All folder icons from {0} are deleted and the folders go back to the default Windows icon. The folders and the files in them aren't touched. To add icons again, use the \"Folder icons\" section."),
        new("Hepsini kaldır", "Remove all"),
        new("{0} klasörün simgesi kaldırıldı; masaüstü birkaç saniye içinde yenilenir.",
            "Removed the icon from {0} folder; the desktop refreshes in a few seconds.",
            "Removed icons from {0} folders; the desktop refreshes in a few seconds."),
        new("Kaldırılacak simge yok: {0}'in verdiği bir klasör simgesi bulunamadı.", "No icons to remove: no folder icons from {0} were found."),
        new("{0} klasöre erişilemediği için dokunulamadı.",
            "{0} folder couldn't be accessed, so it was left as is.",
            "{0} folders couldn't be accessed, so they were left as is."),

        // ---- Gelişmiş: dosya konumları ----
        new("Dosya konumları", "File locations"),
        new("Masaüstü ve ayar klasörleri", "Desktop and settings folders"),
        new("İzlenen masaüstü", "Watched desktop"),
        new("Masaüstü klasörünü aç", "Open desktop folder"),
        new("Ayar ve geçmiş dosyaları", "Settings and history files"),
        new("Ayar klasörünü aç", "Open settings folder"),
        new("Microsoft Store sürümüne ayrılmış klasör; uygulama kaldırılınca Windows içindekileri de siler.",
            "This folder is reserved for the Microsoft Store version; when you uninstall the app, Windows deletes its contents too."),
        new("Taşınabilir mod açık: ayarlar exe'nin yanındaki data klasöründe.", "Portable mode is on: settings are in the data folder next to the exe."),
        new("portable.txt var ama programın klasörüne yazılamıyor; ayarlar şimdilik yukarıdaki klasörde. Programı yazılabilir bir klasöre taşı.",
            "portable.txt is there, but the program's folder can't be written to, so settings are in the folder above for now. Move the program to a folder you can write to."),
        new("Klasör o sırada kullanımda olduğu için {0} adıyla yeniden adlandırılamadı; bir sonraki açılışta yeniden denenecek.",
            "The folder couldn't be renamed to {0} because it was in use at the time; this will be tried again the next time the app starts."),
        new("Taşınabilir kullanım için exe'nin yanına boş bir portable.txt dosyası koy.",
            "To use the app as a portable app, put an empty portable.txt file next to the exe."),

        // ---- Yardım ve Hakkında ----
        new("Yardım", "Help"),
        new("Karşılama", "Setup guide"),
        new("Bölmeleri, otomatik taşımayı ve widget'ları adım adım yeniden kur. Var olanlar silinmez.",
            "Set up panels, auto-move and widgets again, step by step. Nothing you already have is deleted."),
        new("Karşılamayı yeniden aç", "Open the setup guide again"),
        new("Hakkında", "About"),
        new("Microsoft Store sürümü · Güncellemeler Microsoft Store'dan kendiliğinden gelir.",
            "Microsoft Store version · Updates come automatically from the Microsoft Store."),
        new("Taşınabilir sürüm · Güncellemek için yeni zip'i bu klasörün üzerine çıkar; data klasörün korunur.",
            "Portable version · To update, extract the new zip over this folder; your data folder is kept."),
        new("Kurulum sürümü · Güncellemek için indirme sayfasından yeni kurulum dosyasını çalıştır; ayarların korunur.",
            "Installed version · To update, run the new installer from the download page; your settings are kept."),
        new("{0} güncelleme denetlemez ve kendiliğinden internete bağlanmaz. Ayarların ve notların yalnızca bu bilgisayarda.",
            "{0} doesn't check for updates and never connects to the internet on its own. Your settings and notes stay on this PC."),
        new("İndirme sayfasını aç", "Open download page"),
        new("Uygulamadan çık", "Exit app"),
    ]);
}
